### ISSUE TITLE
ESP32 Bluetooth SPP does not connect

### ISSUE THREAD

**Issue by andrebstv** [LK8000/LK8000#1609] opened 2023-02-26 21:56 UTC
Using a Bluetooth serial device made by a ESP32 device.

LK8000 (on android) does correctly identifies and find the device. Though it receives no data. Using the classic Bluetooth Serial Monitor app, available at the playstore, confirms that the ESP32 based device is transmiting data properly.

**Comment by andrebstv** [comment] 2023-02-26 21:59
Do notice the error saying that it`s not possible to open the comm port. Maybe permissions ?

**Comment by andrebstv** [comment] 2023-02-26 22:04
> Using a Bluetooth serial device made by a ESP32 device.
> 
> LK8000 (on android) does correctly identifies and find the device. Though it receives no data. Using the classic Bluetooth Serial Monitor app, available at the playstore, confirms that the ESP32 based device is transmiting data properly.

Checking the latest LK8000 beta manifest it caps the permission at Android 11 (Sdk version 30). Maybe that`s the problem.

**Comment by brunotl** [comment] 2023-02-26 23:28
only BLUETOOTH_CONNECT and BLUETOOTH_SCAN are required since android 12 : 
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher

**Comment by brunotl** [comment] 2023-03-04 17:05
Enable to reproduce ...

**Comment by brunotl** [comment] 2023-03-26 21:38
fixed by commit : 8d24d568f62c2e6c84fa43022745ad886363fc1f

**Closed by brunotl** 2023-03-26 21:38 UTC
Labels: Need Device
